import { CategoryDefinition, Question } from "./types";

export const SCALES = [
  { value: 4, label: "Yes (Full agreement)", labelZh: "是 (完全同意)", short: "Yes" },
  { value: 3, label: "More Yes than No", labelZh: "多半是", short: "Mostly Yes" },
  { value: 2, label: "More No than Yes", labelZh: "多半否", short: "Mostly No" },
  { value: 1, label: "No (Disagreement)", labelZh: "否 (不同意)", short: "No" },
];

export const CATEGORIES: CategoryDefinition[] = [
  // Secondary (1-11)
  { id: "1", name: "Orderliness", nameZh: "有条理", group: "secondary" },
  { id: "2", name: "Cleanliness", nameZh: "清洁", group: "secondary" },
  { id: "3", name: "Punctuality", nameZh: "准时", group: "secondary" },
  { id: "4", name: "Politeness", nameZh: "礼貌", group: "secondary" },
  { id: "5", name: "Openness/Honesty", nameZh: "坦白/诚实", group: "secondary" },
  { id: "6", name: "Achievement", nameZh: "成就/勤奋", group: "secondary" },
  { id: "7", name: "Reliability", nameZh: "可靠", group: "secondary" },
  { id: "8", name: "Thrift", nameZh: "节俭", group: "secondary" },
  { id: "9", name: "Obedience", nameZh: "顺从/纪律", group: "secondary" },
  { id: "10", name: "Justice", nameZh: "公正", group: "secondary" },
  { id: "11", name: "Faithfulness", nameZh: "忠诚", group: "secondary" },
  // Primary (12-19)
  { id: "12", name: "Patience", nameZh: "耐心", group: "primary" },
  { id: "13", name: "Time", nameZh: "时间", group: "primary" },
  { id: "14", name: "Contact", nameZh: "交往", group: "primary" },
  { id: "15", name: "Trust", nameZh: "信任", group: "primary" },
  { id: "16", name: "Hope", nameZh: "希望", group: "primary" },
  { id: "17", name: "Sexuality/Tenderness", nameZh: "温柔/性", group: "primary" },
  { id: "18", name: "Love/Acceptance", nameZh: "爱", group: "primary" },
  { id: "19", name: "Faith/Meaning", nameZh: "信仰/意义", group: "primary" },
  // Conflict (20-23)
  { id: "20", name: "Body", nameZh: "身体", group: "conflict" },
  { id: "21", name: "Achievement", nameZh: "工作/成就", group: "conflict" },
  { id: "22", name: "Contact", nameZh: "关系/交往", group: "conflict" },
  { id: "23", name: "Fantasy", nameZh: "幻想/未来", group: "conflict" },
  // Models (24 split, 25-27)
  { id: "24m", name: "Model: Mother", nameZh: "榜样: 母亲", group: "model" },
  { id: "24f", name: "Model: Father", nameZh: "榜样: 父亲", group: "model" },
  { id: "24o", name: "Model: Others", nameZh: "榜样: 他人", group: "model" },
  { id: "25", name: "You-Parents Relationship", nameZh: "你-父母关系", group: "model" },
  { id: "26", name: "We-Parents-Others", nameZh: "我们-父母-他人关系", group: "model" },
  { id: "27", name: "Original We-Values", nameZh: "原始的我们-价值观", group: "model" },
];

export const QUESTIONS: Question[] = [
  { id: 1, categoryCode: "INFO", text: "I have read the instructions and I am ready to answer all questions openly", textZh: "我已经读过指示，并准备坦白地回答所有问题。" },
  { id: 2, categoryCode: "20a", text: "I feel anger or excitement physically throughout my body.", textZh: "当我感到愤怒或激动时，我全身都有感觉。" },
  { id: 3, categoryCode: "1a", text: "I leave my working place/office/household always orderly", textZh: "我总是把工作场所/办公室/家里整理得很有条理。" },
  { id: 4, categoryCode: "26a", text: "In my childhood I experienced my parents having many social contacts", textZh: "在我小时候，我体验到我的父母有很多社会交往。" },
  { id: 5, categoryCode: "23a", text: "When I'm in trouble, I can't stop thinking about all the potential consequences.", textZh: "当我遇到困难时，我不由自主地想到所有可能发生的后果。" },
  { id: 6, categoryCode: "7c", text: "Reliability is extraordinary important in profession and society", textZh: "在职业和社会上，“为人/处事要可靠”特别重要。" },
  { id: 7, categoryCode: "11a", text: "When I made a decision, I keep to it in any case, despite of all that could come up", textZh: "当我做决定时，无论发生了什么，我都能保持这个决定不变。" },
  { id: 8, categoryCode: "8b", text: "When my relatives spend too much money, easily I feel irritated", textZh: "当我的家人花钱太多时，我很容易生气。" },
  { id: 9, categoryCode: "5c", text: "Openness and honesty are more important than too much respectfulness for others", textZh: "坦白和诚实比尊重他人更为重要。" },
  { id: 10, categoryCode: "16c", text: "In a hopeless looking situation there is always a way out", textZh: "在看起来绝望的处境下，总会有一条路的。" },
  { id: 11, categoryCode: "25a", text: "When my parents had a conflict, they always tried to find a common solution", textZh: "当我的父母有矛盾时，他们总是试图找一个共同的解决办法。" },
  { id: 12, categoryCode: "21a", text: "Achievement and success are my top priorities, especially when I have problems", textZh: "成绩对于我来说最重要，尤其当我遇到问题的时候。" },
  { id: 13, categoryCode: "4b", text: "I prefer people with good behaviour", textZh: "我喜欢与行为良好的人交往。" },
  { id: 14, categoryCode: "2a", text: "I feel only well and clean, when I can take a full bath or shower every day.", textZh: "只有当我每天都洗澡时我才感到舒服和干净。" },
  { id: 15, categoryCode: "12a", text: "I can always be patient, even if something irritates me", textZh: "我总是很耐心，即使有事激怒我的时候。" },
  { id: 16, categoryCode: "9a", text: "I follow orders of a boss or an advise of a person with authority", textZh: "我会遵守上级的指示或采纳权威人士的建议。" },
  { id: 17, categoryCode: "17a", text: "I like very much to be very tender", textZh: "我非常喜欢自己表现得很温和。" },
  { id: 18, categoryCode: "15b", text: "Usually I trust other persons when coming into contact with them", textZh: "一般在与别人交往时我能够信任他们。" },
  { id: 19, categoryCode: "24e", text: "My father was very patient with me when I had been a child", textZh: "在我儿童时代，父亲对我非常有耐心。" },
  { id: 20, categoryCode: "22a", text: "When I'm in trouble, I try always to contact others", textZh: "当我遇到困难时，我总是试图与人分享。" },
  { id: 21, categoryCode: "13b", text: "I will always take my time to meet with others", textZh: "我通常会花时间与别人会面。" },
  { id: 22, categoryCode: "19b", text: "To share my questions about life and death with others is very important", textZh: "与别人分享关于生命和死亡的问题非常重要。" },
  { id: 23, categoryCode: "12b", text: "I stay patient with others even if somebody bothers me", textZh: "即使有人令我生气，我也能保持耐心。" },
  { id: 24, categoryCode: "16b", text: "I believe in a good future for me and my family", textZh: "我相信我和我的家庭都会有一个美好的未来。" },
  { id: 25, categoryCode: "8a", text: "Even having enough money I don't like to spend it", textZh: "即使有足够的钱我也不愿意花。" },
  { id: 26, categoryCode: "27a", text: "My parents talked with us about questions of life philosophy or faith", textZh: "我的父母曾与我们探讨过人生的哲学与信仰。" },
  { id: 27, categoryCode: "10c", text: "Under all circumstances you should treat others with justice and fairness", textZh: "在任何环境重都应该公正公开地对待别人。" },
  { id: 28, categoryCode: "15a", text: "I can always trust myself", textZh: "我能总是信任自己。" },
  { id: 29, categoryCode: "6c", text: "Being lazy causes often bad consequences", textZh: "懒惰总是会带来坏的后果。" },
  { id: 30, categoryCode: "14c", text: "Having good relations is much more important than having money", textZh: "拥有好的关系比拥有财富更重要。" },
  { id: 31, categoryCode: "18a", text: "I can accept myself like I am", textZh: "我能够接纳现实的自己。" },
  { id: 32, categoryCode: "25b", text: "The partnership of my parents was a partnership of love", textZh: "我父母的关系是爱的关系。" },
  { id: 33, categoryCode: "23b", text: "When I am in trouble, I'm very much thinking about it all day and night", textZh: "当我遇到困难时，我会白天黑夜不停地想。" },
  { id: 34, categoryCode: "24b", text: "My mother had been very patient with me as a child", textZh: "在我儿时我母亲对我非常耐心。" },
  { id: 35, categoryCode: "11b", text: "I expect my partner to be always faithful and loyal to me", textZh: "我期望我的配偶对我永远忠诚。" },
  { id: 36, categoryCode: "19a", text: "The meaning of my life concerns me much", textZh: "我非常关注我生命/生活的意义。" },
  { id: 37, categoryCode: "3c", text: "Life becomes unmanageable without punctuality.", textZh: "如果不能准时，你将掌管不了自己的生活。" },
  { id: 38, categoryCode: "12c", text: "With patience you will reach everything", textZh: "有耐心你就会拥有一切。" },
  { id: 39, categoryCode: "26b", text: "My parents had been very tolerant and open with others", textZh: "我的父母对别人既宽容又坦白。" },
  { id: 40, categoryCode: "1b", text: "It drives me crazy when things are messy.", textZh: "没有条理的事情会使我疯狂。" },
  { id: 41, categoryCode: "4c", text: "It is always important to regard the opinion of others", textZh: "考虑别人的意见是很重要的。" },
  { id: 42, categoryCode: "7b", text: "A person on which you can not rely absolutely, never can become my friend", textZh: "一个不能让人绝对信赖的人，永远不会成为我的朋友。" },
  { id: 43, categoryCode: "25c", text: "I have the feeling that my parents treated one another always with justice", textZh: "我感觉我的父母能公正地相互对待。" },
  { id: 44, categoryCode: "5b", text: "I like people telling very directly and openly what they think", textZh: "我喜欢人们能够直接开放地说出他们心中的想法。" },
  { id: 45, categoryCode: "6a", text: "I see myself as very much work and achievement orientated", textZh: "我认为自己是重视工作和成就的人。" },
  { id: 46, categoryCode: "9c", text: "Children should always obey and care about what their parents say", textZh: "孩子应该总是服从和关注父母的话。" },
  { id: 47, categoryCode: "13c", text: "For me there is a life moto: Everything needs time", textZh: "我有一个生活信条：所有事情都需要时间。" },
  { id: 48, categoryCode: "3a", text: "I prefer to be ten minutes earlier than five minutes too late", textZh: "我宁可早到十分钟也不愿迟到五分钟。" },
  { id: 49, categoryCode: "24f", text: "My father had been an important model/example for me in my childhood", textZh: "我小时候父亲是我重要的偶像/榜样。" },
  { id: 50, categoryCode: "20b", text: "Every time I am excited or angry I feel tension or physical discomfort.", textZh: "每当我感到激动或愤怒时，我会感到全身发紧或其他身体上的不舒服。" },
  { id: 51, categoryCode: "22b", text: "When I have difficulties in my job or at home I need the help of others", textZh: "当我在工作上或家里遇到难题时，我需要别人的帮助。" },
  { id: 52, categoryCode: "21b", text: "When I have problems I prefer to work harder", textZh: "当我遇到问题时我会选择更努力地工作。" },
  { id: 53, categoryCode: "11c", text: "Faithfulness is indispensable for a good human character", textZh: "忠诚对于一个好人来说是不可缺少的。" },
  { id: 54, categoryCode: "19c", text: "My life philosophy or faith is very important to give ways to my life", textZh: "我的生活哲学或信仰给了我重要的生活指导。" },
  { id: 55, categoryCode: "27b", text: "My parents life philosophy or faith was a strong basis for them", textZh: "我父母的人生哲学或信仰给了他们强有力的支持。" },
  { id: 56, categoryCode: "2b", text: "I only feel well, when everybody in my home keeps it tidily clean", textZh: "只有当家人都保持整洁时我才会感觉舒服。" },
  { id: 57, categoryCode: "3b", text: "It makes me angry when people are late", textZh: "当有人迟到时我会感到很生气。" },
  { id: 58, categoryCode: "23c", text: "When I'm in trouble I think very much about the meaning of life", textZh: "当我遇到困难时我常会想到生命的意义。" },
  { id: 59, categoryCode: "17c", text: "Tenderness and sexuality are necessary conditions for a partnership", textZh: "对夫妻关系来说温柔和性感是必要的前提条件。" },
  { id: 60, categoryCode: "9b", text: "I expect discipline in family or profession", textZh: "我期望家庭或工作都要有纪律。" },
  { id: 61, categoryCode: "18b", text: "I can also feel well with a person having opinions that differ from mine", textZh: "当别人的意见与我的不同时我也会考虑接受。" },
  { id: 62, categoryCode: "14b", text: "I often have guests", textZh: "我常常请客。" },
  { id: 63, categoryCode: "15c", text: "Trustfulness is a necessary precondition for community life", textZh: "对于集体生活来说，信任是必备的前提条件。" },
  { id: 64, categoryCode: "24a", text: "My mother had much time for me when I had been little", textZh: "在我儿时我的母亲会花很多时间与我在一起。" },
  { id: 65, categoryCode: "10b", text: "I am very sensitive when somebody is not fair", textZh: "当有人不公正时，我会非常敏感。" },
  { id: 66, categoryCode: "8c", text: "The best basis for to be rich is to to be saving", textZh: "富裕的最佳基础是节约。" },
  { id: 67, categoryCode: "2c", text: "Cleanliness of a person shows a clean character", textZh: "清洁的人显示清洁的人品。" },
  { id: 68, categoryCode: "7a", text: "I always keep to what I promised", textZh: "我总是能够信守诺言。" },
  { id: 69, categoryCode: "16a", text: "I always have plans for my life", textZh: "我总是能够计划好自己的生活。" },
  { id: 70, categoryCode: "4a", text: "For me it is easier to say “yes” than to say „no“", textZh: "我总是更容易地说是”而不是说”不”。" },
  { id: 71, categoryCode: "21c", text: "When I'm working I can forget about my problems", textZh: "当我工作时，我能忘掉自己的问题。" },
  { id: 72, categoryCode: "1c", text: "A home should always look orderly", textZh: "一个家庭应该井井有条，只有那样才像个家。" },
  { id: 73, categoryCode: "13a", text: "Despite of my work I have enough time for my interests and hobbies", textZh: "除了工作外我有足够的时间用在自己的兴趣爱好上。" },
  { id: 74, categoryCode: "26c", text: "My parents had many guests and friends", textZh: "我的父母有很多朋友和客人。" },
  { id: 75, categoryCode: "24d", text: "My father took time for me when I had been little", textZh: "当我儿时我的父亲能够花很多时间与我在一起。" },
  { id: 76, categoryCode: "18c", text: "In every person there is something good", textZh: "每个人身上都有优点。" },
  { id: 77, categoryCode: "20c", text: "Often I feel my body in a way that I would like to take medicaments", textZh: "我的身体常让我不得不吃药调理。" },
  { id: 78, categoryCode: "14a", text: "I easily can make friends", textZh: "我很容易交到朋友。" },
  { id: 79, categoryCode: "27c", text: "My parents had been very interested in the meaning of life", textZh: "我的父母对生命的意义很感兴趣。" },
  { id: 80, categoryCode: "6b", text: "I do not feel well when somebody is lazy", textZh: "当有人很懒时，我会感觉很不舒服。" },
  { id: 81, categoryCode: "10a", text: "I judge somebody only when I finally know all reasons for her/his behaviour", textZh: "只有当我了解了一个人的行为的原因时我才判断。" },
  { id: 82, categoryCode: "22c", text: "When I have private or professional problems i need other people around to forget about the problems", textZh: "当我遇到私人的或工作上的难题时，我需要与别人在一起以便忘记这些烦恼。" },
  { id: 83, categoryCode: "17b", text: "With the partner whom I love I want to develop intimacy quickly.", textZh: "当我与我的配偶或男（女）朋友在一起时，我想尽快开始亲热。" },
  { id: 84, categoryCode: "24c", text: "My mother had been a model/example for me", textZh: "我的妈妈曾经是我的偶像/榜样。" },
  { id: 85, categoryCode: "5a", text: "I prefer to say very openly my opinion", textZh: "我能够公开地讲出我的意见与想法。" },
  { id: 86, categoryCode: "24g", text: "As a child I had been often with a person who had more time for me than father and mother", textZh: "小时候有个人与我在一起的时间比父母还要久。" },
  { id: 87, categoryCode: "24h", text: "There was a person in my childhood, which had more patience with me than father or mother", textZh: "小时候有个人比父母还要有耐心。" },
  { id: 88, categoryCode: "24i", text: "There was a person in my childhood, that had been of more importance for me than my parents", textZh: "小时候有个人对我来说比我的父母还要重要。" },
];

export const getTotalQuestions = () => QUESTIONS.length;